CREATE TABLE "AppLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Timestamp" timestamp with time zone NOT NULL,
    "Level" character varying(50),
    "Message" text,
    "MessageTemplate" text,
    "Exception" text,
    "Properties" jsonb,
    "MachineName" character varying(100),
    "UserName" character varying(256),
    "RequestPath" character varying(500),
    "RequestMethod" character varying(10),
    "SourceContext" character varying(500),
    "ActionName" character varying(256),
    CONSTRAINT "PK_AppLogs" PRIMARY KEY ("Id")
);


CREATE TABLE "Branches" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(20) NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Address" text,
    "Phone" text,
    "Email" text,
    "City" text,
    "District" text,
    "IsActive" boolean NOT NULL,
    "SortOrder" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Branches" PRIMARY KEY ("Id")
);


CREATE TABLE "Countries" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "OfficialName" character varying(200),
    "Iso2Code" character varying(2) NOT NULL,
    "Iso3Code" character varying(3) NOT NULL,
    "NumericCode" integer,
    "PhoneCode" character varying(10),
    "CurrencyCode" character varying(3),
    "CurrencyName" character varying(50),
    "CurrencySymbol" character varying(5),
    "FlagEmoji" character varying(10),
    "Region" character varying(50),
    "SubRegion" character varying(50),
    "Capital" character varying(100),
    "Latitude" double precision,
    "Longitude" double precision,
    "DisplayOrder" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Countries" PRIMARY KEY ("Id")
);


CREATE TABLE "Languages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "NativeName" character varying(100),
    "LanguageCulture" character varying(10) NOT NULL,
    "UniqueSeoCode" character varying(5) NOT NULL,
    "Iso3Code" character varying(5),
    "FlagEmoji" character varying(10),
    "FlagImageFileName" character varying(100),
    "Rtl" boolean NOT NULL,
    "IsDefault" boolean NOT NULL,
    "IsGeoTranslationEnabled" boolean NOT NULL,
    "IsActive" boolean NOT NULL,
    "DisplayOrder" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Languages" PRIMARY KEY ("Id")
);


CREATE TABLE "ProductCategories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500),
    "Icon" character varying(100),
    "ImageUrl" character varying(200),
    "ParentId" integer,
    "DisplayOrder" integer NOT NULL,
    "Level" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "Slug" character varying(200),
    "MetaTitle" character varying(200),
    "MetaDescription" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_ProductCategories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProductCategories_ProductCategories_ParentId" FOREIGN KEY ("ParentId") REFERENCES "ProductCategories" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "Roles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Description" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);


CREATE TABLE "VendorCapabilities" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Code" character varying(50) NOT NULL,
    "Description" character varying(500),
    "NameResourceKey" text,
    "Icon" character varying(50),
    "DisplayOrder" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_VendorCapabilities" PRIMARY KEY ("Id")
);


CREATE TABLE "Vendors" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CompanyName" character varying(300) NOT NULL,
    "Email" character varying(200) NOT NULL,
    "Phone" character varying(20) NOT NULL,
    "TaxNumber" character varying(20),
    "TaxOffice" character varying(100),
    "TradeRegistryNo" character varying(50),
    "MersisNo" character varying(20),
    "Website" text,
    "LogoUrl" text,
    "AuthorizedPersonName" text,
    "AuthorizedPersonTitle" text,
    "AuthorizedPersonPhone" text,
    "AuthorizedPersonEmail" text,
    "BankName" text,
    "BankBranch" text,
    "Iban" character varying(34),
    "AccountHolder" text,
    "ActiveCountries" text,
    "VendorStatusId" integer NOT NULL,
    "IsProfileComplete" boolean NOT NULL,
    "IsVerified" boolean NOT NULL,
    "VerifiedAt" timestamp with time zone,
    "VerifiedBy" text,
    "RejectionReason" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Vendors" PRIMARY KEY ("Id")
);


CREATE TABLE "CountryTranslations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CountryId" integer NOT NULL,
    "LanguageCode" character varying(5) NOT NULL,
    "Name" character varying(100) NOT NULL,
    "OfficialName" character varying(200),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_CountryTranslations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CountryTranslations_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES "Countries" ("Id") ON DELETE CASCADE
);


CREATE TABLE "States" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CountryId" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Code" character varying(10),
    "Type" character varying(50),
    "Latitude" double precision,
    "Longitude" double precision,
    "DisplayOrder" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_States" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_States_Countries_CountryId" FOREIGN KEY ("CountryId") REFERENCES "Countries" ("Id") ON DELETE CASCADE
);


CREATE TABLE "LocaleStringResources" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "LanguageId" integer NOT NULL,
    "ResourceName" character varying(500) NOT NULL,
    "ResourceValue" text NOT NULL,
    CONSTRAINT "PK_LocaleStringResources" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LocaleStringResources_Languages_LanguageId" FOREIGN KEY ("LanguageId") REFERENCES "Languages" ("Id") ON DELETE CASCADE
);


CREATE TABLE "RoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" integer NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_RoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoleClaims_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);


CREATE TABLE "CapabilityModules" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CapabilityId" integer NOT NULL,
    "ParentId" integer,
    "PlatformModuleId" integer,
    "Name" character varying(100) NOT NULL,
    "Code" character varying(50),
    "Description" character varying(500),
    "DisplayName" character varying(100),
    "DisplayNameResourceKey" character varying(100),
    "Icon" character varying(50),
    "Route" character varying(200),
    "DisplayOrder" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "IsMenuItem" boolean NOT NULL,
    "IsMenuSection" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_CapabilityModules" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CapabilityModules_CapabilityModules_ParentId" FOREIGN KEY ("ParentId") REFERENCES "CapabilityModules" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_CapabilityModules_CapabilityModules_PlatformModuleId" FOREIGN KEY ("PlatformModuleId") REFERENCES "CapabilityModules" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_CapabilityModules_VendorCapabilities_CapabilityId" FOREIGN KEY ("CapabilityId") REFERENCES "VendorCapabilities" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Addresses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VendorId" integer NOT NULL,
    "AddressTypeId" integer NOT NULL,
    "Title" character varying(100) NOT NULL,
    "Country" character varying(100) NOT NULL,
    "State" character varying(100),
    "City" character varying(100) NOT NULL,
    "District" character varying(100) NOT NULL,
    "AddressLine" character varying(90) NOT NULL,
    "PostalCode" character varying(10),
    "AddressDescription" text,
    "ContactName" character varying(200),
    "ContactPhone" character varying(20),
    "Latitude" double precision,
    "Longitude" double precision,
    "IsDefault" boolean NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Addresses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Addresses_Vendors_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id") ON DELETE CASCADE
);


CREATE TABLE "CompanyRoles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VendorId" integer,
    "CapabilityId" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500),
    "NameResourceKey" character varying(100),
    "IsSystemRole" boolean NOT NULL,
    "IsDefault" boolean NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_CompanyRoles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CompanyRoles_VendorCapabilities_CapabilityId" FOREIGN KEY ("CapabilityId") REFERENCES "VendorCapabilities" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CompanyRoles_Vendors_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Products" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "SKU" character varying(150),
    "Barcode" character varying(100),
    "Description" character varying(4000),
    "ShortDescription" character varying(500),
    "Price" numeric(18,4) NOT NULL,
    "CompareAtPrice" numeric(18,4),
    "CostPrice" numeric(18,4),
    "Currency" character varying(10) NOT NULL,
    "StockQuantity" integer NOT NULL,
    "MinStockLevel" integer,
    "TrackStock" boolean NOT NULL,
    "AllowBackorder" boolean NOT NULL,
    "Weight" numeric(10,3),
    "Length" numeric(10,2),
    "Width" numeric(10,2),
    "Height" numeric(10,2),
    "CategoryId" integer,
    "Tags" character varying(500),
    "DisplayOrder" integer NOT NULL,
    "ProductStatusId" integer NOT NULL,
    "IsFeatured" boolean NOT NULL,
    "PublishedAt" timestamp with time zone,
    "MetaTitle" character varying(200),
    "MetaDescription" character varying(500),
    "Slug" character varying(200),
    "VendorId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Products_ProductCategories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "ProductCategories" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Products_Vendors_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "ProfileImageUrl" text,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastLoginAt" timestamp with time zone,
    "LanguageId" integer,
    "VendorId" integer,
    "VendorRole" integer NOT NULL,
    "IsSystemAdmin" boolean NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_Languages_LanguageId" FOREIGN KEY ("LanguageId") REFERENCES "Languages" ("Id"),
    CONSTRAINT "FK_Users_Vendors_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id") ON DELETE SET NULL
);


CREATE TABLE "VendorCapabilityMappings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VendorId" integer NOT NULL,
    "CapabilityId" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_VendorCapabilityMappings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_VendorCapabilityMappings_VendorCapabilities_CapabilityId" FOREIGN KEY ("CapabilityId") REFERENCES "VendorCapabilities" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_VendorCapabilityMappings_Vendors_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id") ON DELETE CASCADE
);


CREATE TABLE "StateTranslations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StateId" integer NOT NULL,
    "LanguageCode" character varying(5) NOT NULL,
    "Name" character varying(100) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_StateTranslations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StateTranslations_States_StateId" FOREIGN KEY ("StateId") REFERENCES "States" ("Id") ON DELETE CASCADE
);


CREATE TABLE "CompanyRoleModulePermissions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CompanyRoleId" integer NOT NULL,
    "ModuleId" integer NOT NULL,
    "CanView" boolean NOT NULL,
    "CanCreate" boolean NOT NULL,
    "CanEdit" boolean NOT NULL,
    "CanDelete" boolean NOT NULL,
    "CustomPermissions" jsonb,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_CompanyRoleModulePermissions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CompanyRoleModulePermissions_CapabilityModules_ModuleId" FOREIGN KEY ("ModuleId") REFERENCES "CapabilityModules" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CompanyRoleModulePermissions_CompanyRoles_CompanyRoleId" FOREIGN KEY ("CompanyRoleId") REFERENCES "CompanyRoles" ("Id") ON DELETE CASCADE
);


CREATE TABLE "ProductImages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductId" integer NOT NULL,
    "Url" character varying(500) NOT NULL,
    "AltText" character varying(200),
    "Title" character varying(150),
    "DisplayOrder" integer NOT NULL,
    "IsMain" boolean NOT NULL,
    "Width" integer,
    "Height" integer,
    "FileSize" bigint,
    "MimeType" character varying(50),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_ProductImages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProductImages_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);


CREATE TABLE "ProductPriceTiers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductId" integer NOT NULL,
    "MinQuantity" integer NOT NULL,
    "MaxQuantity" integer,
    "Price" numeric(18,4) NOT NULL,
    "Description" character varying(100),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_ProductPriceTiers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProductPriceTiers_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);


CREATE TABLE "CategoryRequests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RequestedName" character varying(200) NOT NULL,
    "Description" character varying(1000),
    "SuggestedParentCategoryId" integer,
    "StatusId" integer NOT NULL,
    "VendorId" integer NOT NULL,
    "RequestedByUserId" integer NOT NULL,
    "ReviewedByUserId" integer,
    "ReviewNote" character varying(500),
    "ReviewedAt" timestamp with time zone,
    "CreatedCategoryId" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_CategoryRequests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CategoryRequests_ProductCategories_CreatedCategoryId" FOREIGN KEY ("CreatedCategoryId") REFERENCES "ProductCategories" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_CategoryRequests_ProductCategories_SuggestedParentCategoryId" FOREIGN KEY ("SuggestedParentCategoryId") REFERENCES "ProductCategories" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_CategoryRequests_Users_RequestedByUserId" FOREIGN KEY ("RequestedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_CategoryRequests_Users_ReviewedByUserId" FOREIGN KEY ("ReviewedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_CategoryRequests_Vendors_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "CompanyRoleUserMappings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "VendorId" integer NOT NULL,
    "CompanyRoleId" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "AssignedByUserId" integer,
    "AssignedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_CompanyRoleUserMappings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CompanyRoleUserMappings_CompanyRoles_CompanyRoleId" FOREIGN KEY ("CompanyRoleId") REFERENCES "CompanyRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CompanyRoleUserMappings_Users_AssignedByUserId" FOREIGN KEY ("AssignedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_CompanyRoleUserMappings_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CompanyRoleUserMappings_Vendors_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id") ON DELETE CASCADE
);


CREATE TABLE "UserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_UserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserClaims_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "UserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_UserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_UserLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "UserRoles" (
    "UserId" integer NOT NULL,
    "RoleId" integer NOT NULL,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "UserTokens" (
    "UserId" integer NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_UserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_UserTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "VendorTeamMembers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VendorId" integer NOT NULL,
    "UserId" integer,
    "Email" character varying(200) NOT NULL,
    "Name" character varying(200),
    "Role" integer NOT NULL,
    "Source" integer NOT NULL,
    "TeamMemberStatusId" integer NOT NULL,
    "InvitationToken" character varying(100),
    "ExpiresAt" timestamp with time zone,
    "ProcessedByUserId" integer,
    "ProcessedAt" timestamp with time zone,
    "Message" character varying(1000),
    "RejectionReason" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_VendorTeamMembers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_VendorTeamMembers_Users_ProcessedByUserId" FOREIGN KEY ("ProcessedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_VendorTeamMembers_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_VendorTeamMembers_Vendors_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Warehouses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(20) NOT NULL,
    "Name" character varying(100) NOT NULL,
    "WarehouseTypeId" integer NOT NULL,
    "Description" character varying(500),
    "AddressId" integer,
    "TotalCapacity" numeric(18,2),
    "CapacityUnit" character varying(20),
    "ManagerUserId" integer,
    "ContactPhone" character varying(20),
    "ContactEmail" character varying(100),
    "OperatingHours" character varying(500),
    "Priority" integer NOT NULL,
    "IsDefault" boolean NOT NULL,
    "IsActive" boolean NOT NULL,
    "VendorId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Warehouses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Warehouses_Addresses_AddressId" FOREIGN KEY ("AddressId") REFERENCES "Addresses" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Warehouses_Users_ManagerUserId" FOREIGN KEY ("ManagerUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Warehouses_Vendors_VendorId" FOREIGN KEY ("VendorId") REFERENCES "Vendors" ("Id") ON DELETE CASCADE
);


CREATE TABLE "ProductWarehouseStocks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductId" integer NOT NULL,
    "WarehouseId" integer NOT NULL,
    "Quantity" numeric(18,4) NOT NULL,
    "ReservedQuantity" numeric(18,4) NOT NULL,
    "MinStockLevel" numeric(18,4),
    "MaxStockLevel" numeric(18,4),
    "ReorderPoint" numeric(18,4),
    "ReorderQuantity" numeric(18,4),
    "BinLocation" character varying(50),
    "Zone" character varying(50),
    "LastStockCheckAt" timestamp with time zone,
    "LastMovementAt" timestamp with time zone,
    "Notes" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_ProductWarehouseStocks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProductWarehouseStocks_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ProductWarehouseStocks_Warehouses_WarehouseId" FOREIGN KEY ("WarehouseId") REFERENCES "Warehouses" ("Id") ON DELETE CASCADE
);


CREATE INDEX "IX_Addresses_VendorId" ON "Addresses" ("VendorId");


CREATE INDEX "IX_AppLogs_Level" ON "AppLogs" ("Level");


CREATE INDEX "IX_AppLogs_Timestamp" ON "AppLogs" ("Timestamp" DESC);


CREATE INDEX "IX_AppLogs_Timestamp_Level" ON "AppLogs" ("Timestamp", "Level");


CREATE UNIQUE INDEX "IX_Branches_Code" ON "Branches" ("Code");


CREATE UNIQUE INDEX "IX_CapabilityModules_CapabilityId_PlatformModuleId" ON "CapabilityModules" ("CapabilityId", "PlatformModuleId") WHERE "PlatformModuleId" IS NOT NULL;


CREATE INDEX "IX_CapabilityModules_ParentId" ON "CapabilityModules" ("ParentId");


CREATE INDEX "IX_CapabilityModules_PlatformModuleId" ON "CapabilityModules" ("PlatformModuleId");


CREATE INDEX "IX_CategoryRequests_CreatedCategoryId" ON "CategoryRequests" ("CreatedCategoryId");


CREATE INDEX "IX_CategoryRequests_RequestedByUserId" ON "CategoryRequests" ("RequestedByUserId");


CREATE INDEX "IX_CategoryRequests_ReviewedByUserId" ON "CategoryRequests" ("ReviewedByUserId");


CREATE INDEX "IX_CategoryRequests_SuggestedParentCategoryId" ON "CategoryRequests" ("SuggestedParentCategoryId");


CREATE INDEX "IX_CategoryRequests_VendorId" ON "CategoryRequests" ("VendorId");


CREATE UNIQUE INDEX "IX_CompanyRoleModulePermissions_CompanyRoleId_ModuleId" ON "CompanyRoleModulePermissions" ("CompanyRoleId", "ModuleId");


CREATE INDEX "IX_CompanyRoleModulePermissions_ModuleId" ON "CompanyRoleModulePermissions" ("ModuleId");


CREATE INDEX "IX_CompanyRoles_CapabilityId" ON "CompanyRoles" ("CapabilityId");


CREATE INDEX "IX_CompanyRoles_VendorId" ON "CompanyRoles" ("VendorId");


CREATE INDEX "IX_CompanyRoleUserMappings_AssignedByUserId" ON "CompanyRoleUserMappings" ("AssignedByUserId");


CREATE INDEX "IX_CompanyRoleUserMappings_CompanyRoleId" ON "CompanyRoleUserMappings" ("CompanyRoleId");


CREATE UNIQUE INDEX "IX_CompanyRoleUserMappings_UserId_VendorId_CompanyRoleId" ON "CompanyRoleUserMappings" ("UserId", "VendorId", "CompanyRoleId");


CREATE INDEX "IX_CompanyRoleUserMappings_VendorId" ON "CompanyRoleUserMappings" ("VendorId");


CREATE UNIQUE INDEX "IX_Countries_Iso2Code" ON "Countries" ("Iso2Code");


CREATE UNIQUE INDEX "IX_Countries_Iso3Code" ON "Countries" ("Iso3Code");


CREATE UNIQUE INDEX "IX_CountryTranslations_CountryId_LanguageCode" ON "CountryTranslations" ("CountryId", "LanguageCode");


CREATE UNIQUE INDEX "IX_Languages_LanguageCulture" ON "Languages" ("LanguageCulture");


CREATE UNIQUE INDEX "IX_Languages_UniqueSeoCode" ON "Languages" ("UniqueSeoCode");


CREATE UNIQUE INDEX "IX_LocaleStringResources_LanguageId_ResourceName" ON "LocaleStringResources" ("LanguageId", "ResourceName");


CREATE INDEX "IX_ProductCategories_ParentId" ON "ProductCategories" ("ParentId");


CREATE UNIQUE INDEX "IX_ProductCategories_Slug" ON "ProductCategories" ("Slug") WHERE "Slug" IS NOT NULL;


CREATE INDEX "IX_ProductImages_ProductId_DisplayOrder" ON "ProductImages" ("ProductId", "DisplayOrder");


CREATE UNIQUE INDEX "IX_ProductPriceTiers_ProductId_MinQuantity" ON "ProductPriceTiers" ("ProductId", "MinQuantity");


CREATE INDEX "IX_Products_Barcode" ON "Products" ("Barcode");


CREATE INDEX "IX_Products_CategoryId" ON "Products" ("CategoryId");


CREATE INDEX "IX_Products_VendorId_ProductStatusId" ON "Products" ("VendorId", "ProductStatusId");


CREATE UNIQUE INDEX "IX_Products_VendorId_SKU" ON "Products" ("VendorId", "SKU") WHERE "SKU" IS NOT NULL;


CREATE UNIQUE INDEX "IX_Products_VendorId_Slug" ON "Products" ("VendorId", "Slug") WHERE "Slug" IS NOT NULL;


CREATE UNIQUE INDEX "IX_ProductWarehouseStocks_ProductId_WarehouseId" ON "ProductWarehouseStocks" ("ProductId", "WarehouseId");


CREATE INDEX "IX_ProductWarehouseStocks_WarehouseId" ON "ProductWarehouseStocks" ("WarehouseId");


CREATE INDEX "IX_RoleClaims_RoleId" ON "RoleClaims" ("RoleId");


CREATE UNIQUE INDEX "RoleNameIndex" ON "Roles" ("NormalizedName");


CREATE UNIQUE INDEX "IX_States_CountryId_Code" ON "States" ("CountryId", "Code") WHERE "Code" IS NOT NULL;


CREATE UNIQUE INDEX "IX_StateTranslations_StateId_LanguageCode" ON "StateTranslations" ("StateId", "LanguageCode");


CREATE INDEX "IX_UserClaims_UserId" ON "UserClaims" ("UserId");


CREATE INDEX "IX_UserLogins_UserId" ON "UserLogins" ("UserId");


CREATE INDEX "IX_UserRoles_RoleId" ON "UserRoles" ("RoleId");


CREATE INDEX "EmailIndex" ON "Users" ("NormalizedEmail");


CREATE INDEX "IX_Users_LanguageId" ON "Users" ("LanguageId");


CREATE INDEX "IX_Users_VendorId" ON "Users" ("VendorId");


CREATE UNIQUE INDEX "UserNameIndex" ON "Users" ("NormalizedUserName");


CREATE UNIQUE INDEX "IX_VendorCapabilities_Code" ON "VendorCapabilities" ("Code");


CREATE INDEX "IX_VendorCapabilityMappings_CapabilityId" ON "VendorCapabilityMappings" ("CapabilityId");


CREATE UNIQUE INDEX "IX_VendorCapabilityMappings_VendorId_CapabilityId" ON "VendorCapabilityMappings" ("VendorId", "CapabilityId");


CREATE UNIQUE INDEX "IX_VendorTeamMembers_InvitationToken" ON "VendorTeamMembers" ("InvitationToken") WHERE "InvitationToken" IS NOT NULL;


CREATE INDEX "IX_VendorTeamMembers_ProcessedByUserId" ON "VendorTeamMembers" ("ProcessedByUserId");


CREATE INDEX "IX_VendorTeamMembers_UserId" ON "VendorTeamMembers" ("UserId");


CREATE INDEX "IX_VendorTeamMembers_VendorId_Email" ON "VendorTeamMembers" ("VendorId", "Email");


CREATE INDEX "IX_VendorTeamMembers_VendorId_UserId" ON "VendorTeamMembers" ("VendorId", "UserId");


CREATE INDEX "IX_Warehouses_AddressId" ON "Warehouses" ("AddressId");


CREATE INDEX "IX_Warehouses_ManagerUserId" ON "Warehouses" ("ManagerUserId");


CREATE UNIQUE INDEX "IX_Warehouses_VendorId_Code" ON "Warehouses" ("VendorId", "Code");


